### ISSUE TITLE
COMMON.txt not found after pip install

### ISSUE THREAD

**Issue by dpritchett** [bradmontgomery/python-ninethreesix#4]
## Error

```
python -m ninethreesix.password
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/ninethreesix/password.py", line 63, in <module>
    p = Password(num_words=args.num, min_len=args.min, max_len=args.max)
  File "/usr/local/lib/python2.7/dist-packages/ninethreesix/password.py", line 36, in __init__
    self.content = self._words()
  File "/usr/local/lib/python2.7/dist-packages/ninethreesix/password.py", line 41, in _words
    content = open(word_list).read()
IOError: [Errno 2] No such file or directory: '/usr/local/lib/python2.7/dist-packages/ninethreesix/COMMON.TXT'
```
## Debug

```
 ls /usr/local/lib/python2.7/dist-packages/ninethreesix/
__init__.py  __init__.pyc  password.py  password.pyc  tests.py  tests.pyc
```

```
ag vers  /usr/local/lib/python2.7/dist-packages/ninethreesix/
/usr/local/lib/python2.7/dist-packages/ninethreesix/__init__.py
1:__version__ = '0.1.0'
```

**Comment by dpritchett** [comment]
I pulled the latest tarball off of pypi and it doesn't seem to include the file:

![image](https://cloud.githubusercontent.com/assets/147981/6994182/4a951088-dad5-11e4-8a21-02c2fbfda886.png)

**Comment by dpritchett** [comment]
Looks like maybe a `package_data` or `data_files` parameter within `setup.py` would help.  Not sure if the file is missing from the PyPI tarball because you forgot to git add it or if they left it out because of the setup.py config.

![image](https://cloud.githubusercontent.com/assets/147981/6994199/e8206014-dad5-11e4-847b-de75d1d973bc.png)

**Comment by dpritchett** [comment]
0.1.1 seems to work, thanks!

```
python -m ninethreesix.password

Lipari-white-Tiflis
```
